### ISSUE TITLE
Self hosted with pre-loaded folder (scripts, flows)

### ISSUE THREAD

**Issue by razuro** [windmill-labs/windmill-sync-example#66]
Hi, do let me know if it's not ok to ask question here instead. A bit of background, I've gone thru the docs for self-hosted and have been testing Windmill for weeks. I can say I love it so far. My question, is there a way to spin up docker with a predefine folder path of scripts, flows, etc?

**Comment by rubenfiszel** [comment]
The one way to do this would be to use the windmill CLI as an init script in one of your worker to sync push against your volume

**Comment by razuro** [comment]
Thank you for the prompt reply. Yes, I think for my use case, currently that's the only way how to do it. Thanks again, and keep up the good work!
